import { z } from "zod";

export const generalDataSchema = z.object({
  etapas_ofertadas: z.array(z.string()).optional(),
  modalidades_ofertadas: z.array(z.string()).optional(),
  ambientes: z.array(z.string()).optional(),
  problemas_eletricos: z.array(z.string()).optional(),
  tipo_predio: z.string().optional(),
  possui_anexos: z.enum(["Sim", "Não"]).optional(),
  qtd_anexos: z.coerce.number().optional(),
  tipo_predio_anexo: z.string().optional(),
  turmas_manha: z.coerce.number().optional(),
  turmas_tarde: z.coerce.number().optional(),
  turmas_noite: z.coerce.number().optional(),
  total_alunos: z.coerce.number().optional(),
  alunos_pcd: z.coerce.number().optional(),
  alunos_rural: z.coerce.number().optional(),
  alunos_urbana: z.coerce.number().optional(),
  muro_cerca: z.string().optional(),
  perimetro_fechado: z.string().optional(),
  situacao_estrutura: z.string().optional(),
  data_ultima_reforma: z.string().optional(),
  quadra_coberta: z.enum(["Sim", "Não"]).optional(),
  qtd_quadras: z.coerce.number().optional(),
  banda_fanfarra: z.enum(["Sim", "Não"]).optional(),
  banheiros_alunos: z.coerce.number().optional(),
  banheiros_prof: z.coerce.number().optional(),
  banheiros_chuveiro: z.coerce.number().optional(),
  banheiros_vasos_funcionais: z.string().optional(),
  salas_climatizadas: z.coerce.number().optional(),
  energia: z.string().optional(),
  transformador: z.enum(["Sim", "Não"]).optional(),
  rede_eletrica_atende: z.string().optional(),
  estrutura_climatizacao: z.string().optional(),
  suporta_novos_equipamentos: z.string().optional(),
  cameras_funcionamento: z.string().optional(),
  cameras_cobrem: z.string().optional(),
});

export type GeneralDataFormValues = z.infer<typeof generalDataSchema>;